### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by HappyDay-design** [ZKBig/XRouting#1]
Hello

Thank you for sharing your models.
I followed your instructions to build the environment.
I had error when running ` python train.py --run=PPO`

(RolloutWorker pid=45995) Loading additional-files from '/home/osboxes/Desktop/XRouting/sumo_scenario/exercise.add.xml'... 
(RolloutWorker pid=45995) Loading of additional-files failed.
(RolloutWorker pid=45996) Loading net-file from '/home/osboxes/Desktop/XRouting/sumo_scenario/scenario.net.xml'... done (6ms).
(RolloutWorker pid=45996) Loading additional-files from '/home/osboxes/Desktop/XRouting/sumo_scenario/exercise.add.xml'... 
(RolloutWorker pid=45996) Loading of additional-files failed.
Traceback (most recent call last):
  File "train.py", line 135, in <module>
    local_dir=training_results_dir
  File "/home/osboxes/anaconda3/envs/Py/lib/python3.7/site-packages/ray/tune/tune.py", line 695, in run
    raise TuneError("Trials did not complete", incomplete_trials)

**Comment by HappyDay-design** [comment]
Do you have papers about your models

**Comment by Clown1206** [comment]
> Do you have papers about your models

This is the paper for the code：XRouting: Explainable Vehicle Rerouting for Urban Road Congestion Avoidance using Deep 
 Reinforcement Learning. I have also seen your problem in other code. My research is path planning，maybe we can communicate and discuss it. My email is：809663097@qq.com

**Comment by ZKBig** [comment]
> Hello
> 
> Thank you for sharing your models. I followed your instructions to build the environment. I had error when running ` python train.py --run=PPO`
> 
> (RolloutWorker pid=45995) Loading additional-files from '/home/osboxes/Desktop/XRouting/sumo_scenario/exercise.add.xml'... (RolloutWorker pid=45995) Loading of additional-files failed. (RolloutWorker pid=45996) Loading net-file from '/home/osboxes/Desktop/XRouting/sumo_scenario/scenario.net.xml'... done (6ms). (RolloutWorker pid=45996) Loading additional-files from '/home/osboxes/Desktop/XRouting/sumo_scenario/exercise.add.xml'... (RolloutWorker pid=45996) Loading of additional-files failed. Traceback (most recent call last): File "train.py", line 135, in local_dir=training_results_dir File "/home/osboxes/anaconda3/envs/Py/lib/python3.7/site-packages/ray/tune/tune.py", line 695, in run raise TuneError("Trials did not complete", incomplete_trials)

Thanks for your concern of this project :), and sorry for replying lately. It seems that the file named 'exercise.add.xml' cannot be loaded successfully, but it works well in my environment. Please be sure that the file does exist in the corresponding directory and try to run this program more times to check if this problem is solved or not. If you still cannot solve this problem, feel free to write here. Thanks again!

**Comment by ZKBig** [comment]
> > Do you have papers about your models
> 
> This is the paper for the code：XRouting: Explainable Vehicle Rerouting for Urban Road Congestion Avoidance using Deep Reinforcement Learning. I have also seen your problem in other code. My research is path planning，maybe we can communicate and discuss it. My email is：[809663097@qq.com](mailto:809663097@qq.com)

Thanks for your replying, if you have any question about this paper and the codes, please feel free to chat here :)
