### ISSUE TITLE
About 'next_state'

### ISSUE THREAD

**Issue by Clown1206** [ZKBig/XRouting#2]
Hi, Thank you for open-source your code, I have a question: when the agent makes an action according to the current state, how can we get the next state? I don't seem to have found the relevant explanation and method in your paper and code。

**Comment by ZKBig** [comment]
> 

Thanks for your concern of this project :), and sorry for replying late. The next state, which is quite important in this project, can be obtained as the return values of the method named 'step(action)' in the line 332 of the directory 'XRouting/rl/env/dynamic_rerouting_env.py'. If you have any question, please feel free to write here. Thanks again!

**Comment by ZKBig** [comment]
> Hi, Thank you for open-source your code, I have a question: when the agent makes an action according to the current state, how can we get the next state? I don't seem to have found the relevant explanation and method in your paper and code。
Thanks for your concern of this project :), and sorry for replying late. The next state, which is quite important in this project, can be obtained as the return values of the method named 'step(action)' in the line 332 of the directory 'XRouting/rl/env/dynamic_rerouting_env.py'. If you have any question, please feel free to write here. Thanks again!
